package com.ucm.dasi.catan.request;

public enum RequestType {
  BUILD_CONNECTION,
  BUILD_INITIAL_CONNECTION,
  BUILD_INITIAL_STRUCTURE,
  BUILD_STRUCTURE,
  END_TURN,
  START_TURN,
  UPGRADE_STRUCTURE,
}
