package io.github.notaphplover.catan.core.request;

public enum RequestType {
  BUILD_CONNECTION,
  BUILD_INITIAL_CONNECTION,
  BUILD_INITIAL_STRUCTURE,
  BUILD_STRUCTURE,
  END_TURN,
  START_TURN,
  TRADE,
  TRADE_AGREEMENT,
  TRADE_CONFIRMATION,
  TRADE_DISCARD,
  UPGRADE_STRUCTURE,
}
